version: '3.8'

services:
  # api-smart-fast-pay:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: laravel-app-image
  #   container_name: api-smart-fast-pay
  #   restart: unless-stopped
  #   working_dir: /var/www/
  #   volumes:
  #     - ./:/var/www
  #     - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #   networks:
  #     - app-network
  #   ports:
  #     - "8000:80"
  #   environment:
  #     - APP_ENV=local
  #     - APP_DEBUG=true
  #     - APP_KEY=base64:YOUR_APP_KEY_HERE
  #     - DB_CONNECTION=mysql
  #     - DB_HOST=db-smart-fast-pay
  #     - DB_PORT=3306
  #     - DB_DATABASE=smart_fast_pay
  #     - DB_USERNAME=admin
  #     - DB_PASSWORD=123456

  db-smart-fast-pay:
    image: mysql:5.7
    container_name: db-smart-fast-pay
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "smart_fast_pay"
      MYSQL_ROOT_PASSWORD: "root123456"
      MYSQL_PASSWORD: "123456"
      MYSQL_USER: "admin"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge